version: "3.8"
services:
  php:
    build: .docker/php/
    volumes:
      - .:/var/www/html
    links:
      - mysql

  nginx:
    image: nginx:1.19
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    ports:
      - "33060:3306"

volumes:
  dbdata: